### ISSUE TITLE
🛑 Debo Cloud Foca Software is down

### ISSUE THREAD

**Issue by ArielGQ** [Foca-Software/status#196]
In [`f119917`](https://github.com/Foca-Software/status/commit/f1199171e0f09054691a8cda3e91ff7cee894fa9
), Debo Cloud Foca Software (https://debocloud.focasoftware.com/web/login) was **down**:
- HTTP code: 500
- Response time: 3133 ms

**Comment by ArielQ-MDZ** [comment]
Service Disabled
